version: '3.7'

services:
  composite_template:
    image: "composite_template:dev"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=true